//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Likes = new HashSet<Likes>();
            this.Pictures = new HashSet<Pictures>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Likes> Likes { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
